# Generated by Django 5.0.14 on 2026-06-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal', verbose_name='Sucursal'),
        ),
    ]
