# Generated by Django 5.0.14 on 2026-06-22 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursales', '0001_initial'),
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Microchip')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('sucursal_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal', verbose_name='Sucursal de Registro')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutores.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
