# Generated by Django 5.0.14 on 2026-06-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tiene_acceso_cruzado',
            field=models.BooleanField(default=False, help_text='Autorización del tutor para que el paciente sea visible en todas las sucursales', verbose_name='Acceso multi-sucursal autorizado'),
        ),
    ]
