# Generated by Django 5.0.14 on 2026-06-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_tiene_acceso_cruzado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='codigo_acceso',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código de autorización'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del código'),
        ),
    ]
