# Generated by Django 5.0.14 on 2026-06-22 21:26

import apps.fichas_medicas.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Temperatura (°C)')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('medicamentos', models.TextField(blank=True, default='', verbose_name='Medicamentos')),
                ('examenes', models.TextField(blank=True, default='', verbose_name='Exámenes')),
                ('codigo_acceso', models.CharField(default=apps.fichas_medicas.models.generar_codigo_acceso, editable=False, max_length=8, unique=True, verbose_name='Código de Acceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.doctor', verbose_name='Doctor')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente', verbose_name='Mascota')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
    ]
