# Generated by Django 5.0.14 on 2026-06-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_medicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
    ]
