# Generated by Django 5.0.14 on 2026-06-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta crédito'), ('tarjeta_debito', 'Tarjeta débito'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutores.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Emisión'),
        ),
    ]
