# Generated by Django 5.0.14 on 2026-06-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('asistente', 'Asistente')], default='asistente', max_length=20, verbose_name='Rol'),
        ),
    ]
